# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "roda", "~> 3.54"
gem "roda-websockets", "~> 0.1.0"
gem "msgpack", "~> 1.5"
gem "falcon", "~> 0.39.2"

